<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLanguagesTable extends Migration
{
    /**
     * Schema table name to migrate
     * @var string
     */
    public $tableName = 'languages';

    /**
     * Run the migrations.
     * @table languages
     *
     * @return void
     */
    public function up()
    {
        Schema::create($this->tableName, function (Blueprint $table) {
            $table->engine = 'MyISAM';
            $table->increments('id');
            $table->tinyInteger('rtl')->default('0');
            $table->tinyInteger('is_default')->default('0');
            $table->string('language', 50);
            $table->text('home')->nullable()->default(null);
            $table->text('fh')->nullable()->default(null);
            $table->text('fht')->nullable()->default(null);
            $table->text('h')->nullable()->default(null);
            $table->text('vt')->nullable()->default(null);
            $table->text('gt')->nullable()->default(null);
            $table->text('vdn')->nullable()->default(null);
            $table->text('about')->nullable()->default(null);
            $table->text('blog')->nullable()->default(null);
            $table->text('blogs')->nullable()->default(null);
            $table->text('faq')->nullable()->default(null);
            $table->text('faqs')->nullable()->default(null);
            $table->text('maq')->nullable()->default(null);
            $table->text('contact')->nullable()->default(null);
            $table->text('con')->nullable()->default(null);
            $table->text('cop')->nullable()->default(null);
            $table->text('coe')->nullable()->default(null);
            $table->text('cor')->nullable()->default(null);
            $table->text('signin')->nullable()->default(null);
            $table->text('sie')->nullable()->default(null);
            $table->text('spe')->nullable()->default(null);
            $table->text('signup')->nullable()->default(null);
            $table->text('suf')->nullable()->default(null);
            $table->text('suph')->nullable()->default(null);
            $table->text('sue')->nullable()->default(null);
            $table->text('sup')->nullable()->default(null);
            $table->text('sucp')->nullable()->default(null);
            $table->text('dashboard')->nullable()->default(null);
            $table->text('edit')->nullable()->default(null);
            $table->text('reset')->nullable()->default(null);
            $table->text('logout')->nullable()->default(null);
            $table->text('cp')->nullable()->default(null);
            $table->text('np')->nullable()->default(null);
            $table->text('rnp')->nullable()->default(null);
            $table->text('chnp')->nullable()->default(null);
            $table->text('bgs')->nullable()->default(null);
            $table->text('rds')->nullable()->default(null);
            $table->text('hcs')->nullable()->default(null);
            $table->text('lns')->nullable()->default(null);
            $table->text('lm')->nullable()->default(null);
            $table->text('vd')->nullable()->default(null);
            $table->text('ston')->nullable()->default(null);
            $table->text('s')->nullable()->default(null);
            $table->text('fl')->nullable()->default(null);
            $table->text('sm')->nullable()->default(null);
            $table->text('fpw')->nullable()->default(null);
            $table->text('fpt')->nullable()->default(null);
            $table->text('fpe')->nullable()->default(null);
            $table->text('fpb')->nullable()->default(null);
            $table->text('cn')->nullable()->default(null);
            $table->text('al')->nullable()->default(null);
            $table->text('bg')->nullable()->default(null);
            $table->text('dni')->nullable()->default(null);
            $table->text('search')->nullable()->default(null);
            $table->text('ec')->nullable()->default(null);
            $table->text('sbg')->nullable()->default(null);
            $table->text('ss')->nullable()->default(null);
            $table->text('bs')->nullable()->default(null);
            $table->text('dopd')->nullable()->default(null);
            $table->text('doo')->nullable()->default(null);
            $table->text('dol')->nullable()->default(null);
            $table->text('doa')->nullable()->default(null);
            $table->text('doe')->nullable()->default(null);
            $table->text('dor')->nullable()->default(null);
            $table->text('dopr')->nullable()->default(null);
            $table->text('doc')->nullable()->default(null);
            $table->text('doci')->nullable()->default(null);
            $table->text('dosp')->nullable()->default(null);
            $table->text('don')->nullable()->default(null);
            $table->text('doem')->nullable()->default(null);
            $table->text('dom')->nullable()->default(null);
            $table->text('fname')->nullable()->default(null);
            $table->text('cup')->nullable()->default(null);
            $table->text('pp')->nullable()->default(null);
            $table->text('app')->nullable()->default(null);
            $table->text('size')->nullable()->default(null);
            $table->text('md')->nullable()->default(null);
            $table->text('amf')->nullable()->default(null);
            $table->text('doct')->nullable()->default(null);
            $table->text('doad')->nullable()->default(null);
            $table->text('doph')->nullable()->default(null);
            $table->text('dofx')->nullable()->default(null);
            $table->text('dofpl')->nullable()->default(null);
            $table->text('dotpl')->nullable()->default(null);
            $table->text('dogpl')->nullable()->default(null);
            $table->text('dolpl')->nullable()->default(null);
            $table->text('doeml')->nullable()->default(null);
            $table->text('doupl')->nullable()->default(null);
            $table->text('supl')->nullable()->default(null);
            $table->text('success')->nullable()->default(null);
            $table->text('dttl')->nullable()->default(null);
            $table->text('ddesc')->nullable()->default(null);
            $table->text('ppr')->nullable()->default(null);
            $table->text('fpr')->nullable()->default(null);
            $table->text('cremove')->nullable()->default(null);
            $table->text('cimage')->nullable()->default(null);
            $table->text('cproduct')->nullable()->default(null);
            $table->text('cedit')->nullable()->default(null);
            $table->text('cquantity')->nullable()->default(null);
            $table->text('cupice')->nullable()->default(null);
            $table->text('cst')->nullable()->default(null);
            $table->text('ccs')->nullable()->default(null);
            $table->text('cpc')->nullable()->default(null);
            $table->text('odetails')->nullable()->default(null);
            $table->text('bdetails')->nullable()->default(null);
            $table->text('ship')->nullable()->default(null);
            $table->text('onow')->nullable()->default(null);
            $table->text('ships')->nullable()->default(null);
            $table->text('shipss')->nullable()->default(null);
            $table->text('pickup')->nullable()->default(null);
            $table->text('pickups')->nullable()->default(null);
            $table->text('onotes')->nullable()->default(null);
            $table->text('tid')->nullable()->default(null);
            $table->text('pickupss')->nullable()->default(null);
            $table->text('blogss')->nullable()->default(null);
            $table->text('blogsss')->nullable()->default(null);
            $table->text('contacts')->nullable()->default(null);
            $table->text('ctry')->nullable()->default(null);
            $table->text('sctry')->nullable()->default(null);
            $table->text('cpn')->nullable()->default(null);
            $table->text('ecpn')->nullable()->default(null);
            $table->text('acpn')->nullable()->default(null);
            $table->text('ds')->nullable()->default(null);
            $table->text('ft')->nullable()->default(null);
            $table->text('review_title')->nullable()->default(null);
            $table->text('video_title')->nullable()->default(null);
            $table->text('enter_code')->nullable()->default(null);
            $table->text('support')->nullable()->default(null);
            $table->text('product_detail')->nullable()->default(null);
            $table->text('hot_sale')->nullable()->default(null);
            $table->text('latest_special')->nullable()->default(null);
            $table->text('big_sale')->nullable()->default(null);
            $table->text('featured_product')->nullable()->default(null);
            $table->text('new_arrival')->nullable()->default(null);
            $table->text('shop_now')->nullable()->default(null);
            $table->text('week')->nullable()->default(null);
            $table->text('day')->nullable()->default(null);
            $table->text('hour')->nullable()->default(null);
            $table->text('minute')->nullable()->default(null);
            $table->text('second')->nullable()->default(null);
            $table->text('view_website')->nullable()->default(null);
            $table->text('wish_list')->nullable()->default(null);
            $table->text('favorite_product')->nullable()->default(null);
            $table->text('order_processing')->nullable()->default(null);
            $table->text('order_completed')->nullable()->default(null);
            $table->text('view_all')->nullable()->default(null);
            $table->text('all_categories')->nullable()->default(null);
            $table->text('wishlists')->nullable()->default(null);
            $table->text('wish_head')->nullable()->default(null);
            $table->text('others')->nullable()->default(null);
            $table->text('colors')->nullable()->default(null);
            $table->text('shop_name')->nullable()->default(null);
            $table->text('vendor_description')->nullable()->default(null);
            $table->text('linked_accounts')->nullable()->default(null);
            $table->text('signinup')->nullable()->default(null);
            $table->text('vendor_registration')->nullable()->default(null);
            $table->text('vshop_name')->nullable()->default(null);
            $table->text('owner_name')->nullable()->default(null);
            $table->text('shop_number')->nullable()->default(null);
            $table->text('shop_address')->nullable()->default(null);
            $table->text('reg_number')->nullable()->default(null);
            $table->text('message')->nullable()->default(null);
            $table->text('optional')->nullable()->default(null);
            $table->text('sale')->nullable()->default(null);
            $table->text('welcome')->nullable()->default(null);
            $table->text('user_dashboard')->nullable()->default(null);
            $table->text('conv')->nullable()->default(null);
            $table->text('new_conv')->nullable()->default(null);
            $table->text('no_conv')->nullable()->default(null);
            $table->text('affilate_bonus')->nullable()->default(null);
            $table->text('current_balance')->nullable()->default(null);
            $table->text('item_sold')->nullable()->default(null);
            $table->text('total_earning')->nullable()->default(null);
            $table->text('clear')->nullable()->default(null);
            $table->text('customer')->nullable()->default(null);
            $table->text('favorite_seller')->nullable()->default(null);
            $table->text('messages')->nullable()->default(null);
            $table->text('purchased_item')->nullable()->default(null);
            $table->text('affilate_settings')->nullable()->default(null);
            $table->text('affilate_withdraw')->nullable()->default(null);
            $table->text('affilate_code')->nullable()->default(null);
            $table->text('vendor_products')->nullable()->default(null);
            $table->text('vendor_orders')->nullable()->default(null);
            $table->text('withdraw')->nullable()->default(null);
            $table->text('settings')->nullable()->default(null);
            $table->text('sliders')->nullable()->default(null);
            $table->text('shop_description')->nullable()->default(null);
            $table->text('shipping_cost')->nullable()->default(null);
            $table->text('social_link')->nullable()->default(null);
            $table->text('vendor_apply')->nullable()->default(null);
            $table->text('availability')->nullable()->default(null);
            $table->text('wishlist_add')->nullable()->default(null);
            $table->text('quick_view')->nullable()->default(null);
            $table->text('compare')->nullable()->default(null);
            $table->text('product_condition')->nullable()->default(null);
            $table->text('shipping_time')->nullable()->default(null);
            $table->text('watch_video')->nullable()->default(null);
            $table->text('add_seller')->nullable()->default(null);
            $table->text('contact_seller')->nullable()->default(null);
            $table->text('phone_number')->nullable()->default(null);
            $table->text('send_message')->nullable()->default(null);
            $table->text('send_to')->nullable()->default(null);
            $table->text('new_message')->nullable()->default(null);
            $table->text('vendor_subject')->nullable()->default(null);
            $table->text('vendor_message')->nullable()->default(null);
            $table->text('vendor_send')->nullable()->default(null);
            $table->text('platform')->nullable()->default(null);
            $table->text('region')->nullable()->default(null);
            $table->text('licence_type')->nullable()->default(null);
            $table->text('comment_login')->nullable()->default(null);
            $table->text('comment_review')->nullable()->default(null);
            $table->text('product_favorite')->nullable()->default(null);
            $table->text('facebook_login')->nullable()->default(null);
            $table->text('google_login')->nullable()->default(null);
            $table->text('digital_login')->nullable()->default(null);
            $table->text('tax')->nullable()->default(null);
            $table->text('comment')->nullable()->default(null);
            $table->text('comments')->nullable()->default(null);
            $table->text('write_comment')->nullable()->default(null);
            $table->text('write_reply')->nullable()->default(null);
            $table->text('edit_button')->nullable()->default(null);
            $table->text('reply_button')->nullable()->default(null);
            $table->text('remove')->nullable()->default(null);
            $table->text('update_comment')->nullable()->default(null);
            $table->text('edit_comment')->nullable()->default(null);
            $table->text('edit_reply')->nullable()->default(null);
            $table->text('compare_title')->nullable()->default(null);
            $table->text('compare_rating')->nullable()->default(null);
            $table->text('compare_vendor')->nullable()->default(null);
            $table->text('compare_description')->nullable()->default(null);
            $table->text('compare_available')->nullable()->default(null);
            $table->text('compare_cart')->nullable()->default(null);
            $table->text('no_compare')->nullable()->default(null);
            $table->text('to_review')->nullable()->default(null);
            $table->text('product_review')->nullable()->default(null);
            $table->text('view_replies')->nullable()->default(null);
            $table->text('cancel_edit')->nullable()->default(null);
            $table->text('see_more')->nullable()->default(null);
            $table->text('see_less')->nullable()->default(null);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
     public function down()
     {
       Schema::dropIfExists($this->tableName);
     }
}

